// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Jets            string
	Languages       string
	Pilots          string
	PilotsLanguages string
}{
	Jets:            "jets",
	Languages:       "languages",
	Pilots:          "pilots",
	PilotsLanguages: "pilots_languages",
}
